version: '3'
services:
  grouchbot:
    image: guyot/grouchbot
    build:
      context: .
      dockerfile: ./docker/Dockerfile-Prod
      args:
        - ENV=prod
        - PORT=8080
    ports:
      - 8080
