version: '3'
services:
  grouchbot:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        - ENV=$ENV
        - PORT=$PORT
    volumes:
      - ./config:/usr/src/grouchbot/config
      - ./src:/usr/src/grouchbot/src
  redis:
    image: redis:alpine
  ngrok:
    image: wernight/ngrok
    ports:
      - 4040
    environment:
      - NGROK_AUTH=$NGROK_AUTH_TOKEN
      - NGROK_SUBDOMAIN=$NGROK_SUBDOMAIN
      - NGROK_BINDTLS=true
      - NGROK_PORT=grouchbot:$PORT
