---
apiVersion: getambassador.io/v2
kind: Mapping
metadata: 
  name: grouchbot
spec:     
  prefix: /grouchbot/
  rewrite: /
  service: grouchbot:80
---
apiVersion: v1
kind: Service
metadata:
  name: grouchbot
  namespace: default
spec:
  ports:
  - name: http-grouchbot
    port: 80
    targetPort: 8080
  selector:
    app: grouchbot
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grouchbot
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grouchbot
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: grouchbot
        version: 1.0.0
    spec:
      containers:
      - name: grouchbot
        image: guyot/grouchbot:latest
        ports:
        - name: http-grouchbot
          containerPort: 8080
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 8080
          initialDelaySeconds: 3
        readinessProbe:
          httpGet:
            path: /readycheck
            port: 8080
          initialDelaySeconds: 3

