From node:14.14.0-alpine3.12

WORKDIR /usr/src/grouchbot

# Install dependencies
COPY package*.json ./
RUN npm ci --only=production

# Write source and configuration files
COPY src/ ./src/
COPY config/ ./config/

ARG ENV
ENV ENV=$ENV

ARG PORT
ENV PORT=$PORT

ENTRYPOINT [ "node", "./src/startup.js" ]
